export const trendingItems = [
  {
    productImage: "/images/products-images/camera-image.jpg",
    productPrice: "150",
    imageAlt: "Camera Image",
    productName: "Camera",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/camera",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/cream-image.jpg",
    productPrice: "130",
    imageAlt: "Camera Image",
    productName: "Lotion",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/cream",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/speaker-image.jpg",
    productPrice: "200",
    imageAlt: "Camera Image",
    productName: "Speaker",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/speaker",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/watch-image.jpg",
    productPrice: "250",
    imageAlt: "Camera Image",
    productName: "Watch",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/watch",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/camera-image.jpg",
    productPrice: "150",
    imageAlt: "Camera Image",
    productName: "Camera",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/camera",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/cream-image.jpg",
    productPrice: "130",
    imageAlt: "Camera Image",
    productName: "Cream",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/cream",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/speaker-image.jpg",
    productPrice: "200",
    imageAlt: "Camera Image",
    productName: "Speaker",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/speaker",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/watch-image.jpg",
    productPrice: "250",
    imageAlt: "Camera Image",
    productName: "Watch",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/watch",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/camera-image.jpg",
    productPrice: "150",
    imageAlt: "Camera Image",
    productName: "Camera",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/camera",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/cream-image.jpg",
    productPrice: "130",
    imageAlt: "Camera Image",
    productName: "Lotion",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/cream",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/speaker-image.jpg",
    productPrice: "200",
    imageAlt: "Camera Image",
    productName: "Speaker",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/speaker",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/watch-image.jpg",
    productPrice: "250",
    imageAlt: "Camera Image",
    productName: "Watch",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/watch",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/camera-image.jpg",
    productPrice: "150",
    imageAlt: "Camera Image",
    productName: "Camera",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/camera",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/cream-image.jpg",
    productPrice: "130",
    imageAlt: "Camera Image",
    productName: "Cream",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/cream",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/speaker-image.jpg",
    productPrice: "200",
    imageAlt: "Camera Image",
    productName: "Speaker",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/speaker",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
  {
    productImage: "/images/products-images/watch-image.jpg",
    productPrice: "250",
    imageAlt: "Camera Image",
    productName: "watch",
    profilePic: "/images/users/user-four.jpg",
    profileAlt: "User Image",
    url: "/show-case/watch",
    comments: [
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Jahangir Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-one.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Nadeem Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-two.jpg",
        imageAlt: "User Profile",
      },
      {
        name: "Hassan Khan",
        text: "Amzaing Product Keep it Up",
        image: "./images/users/user-three.jpg",
        imageAlt: "User Profile",
      },
    ],
  },
];
